apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: test
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/crds
  prune: true
